#!/bin/bash

HOST_IP=$(ipconfig getifaddr en0)
EPICS_PORT=59001
ENV_VARS="EPICS_CA_ADDR_LIST=127.0.0.1:$EPICS_PORT EPICS_CA_AUTO_ADDR_LIST=NO EPICS_CA_NAME_SERVERS=127.0.0.1:$EPICS_PORT" 

ssh dev3 -R $EPICS_PORT:localhost:5064 $ENV_VARS edm -x -eolc -m "area=und1,x=14,EVGLOC=IN20,subsys=mc,y=6,U=USEG:SIM,B=BFW:MMF:HXR1,N=1,USEG=U01,ioc=IOC:USEGSIM:UC01,crat=CRAT:USEGSIM:UC01,UN1=USEG:SIM" ID4SSysControl.edl
